Use `eleventy-plugin-icons`
ryanccn/ryanccn.dev pull request #194
Opened 2023-05-22 22:16 UTC by uncenter

Simplify icons by switching to `eleventy-plugin icons`. Condenses `lucide` and `simpleicon` shortcodes into one singular `icon` shortcode:

`{% lucide 'example, 'classes' %}` --> `{% icon 'lucide:example, class='classes' %}`
`{% simpleicon 'example, 'classes' %}` --> `{% icon 'simpleicon:example, class='classes' %}`

My calculations also show that there may be a slight performance increase.
Using `eleventy-plugin-icons`:
<img width="1056" alt="SCR-20230522-ppxs" src="https://github.com/ryanccn/ryanccn.dev/assets/47499684/d58c0414-7289-431b-94a6-dc46faf2eea9">
<img width="976" alt="SCR-20230522-pqib" src="https://github.com/ryanccn/ryanccn.dev/assets/47499684/960c1ee5-b1ce-43e3-877c-69fee2c8e6ad">
<img width="1021" alt="SCR-20230522-pqqz" src="https://github.com/ryanccn/ryanccn.dev/assets/47499684/2f2aa5e8-d4fb-42b1-bf15-0cfd6c69f969">

A mean average of ~2.33ms per call 763 times is 1.77779s.

Using `lucide` and `simpleicon` shortcodes (I only did two I'm lazy):
<img width="969" alt="SCR-20230522-pssk" src="https://github.com/ryanccn/ryanccn.dev/assets/47499684/c8b1a03e-f237-4e95-84cb-22531726918b">
<img width="987" alt="SCR-20230522-ptde" src="https://github.com/ryanccn/ryanccn.dev/assets/47499684/e77c2902-4326-44b6-8671-33f012a7dbc5">

For the `lucide` shortcode, ~2ms per call 290 times is 0.58s. For the `simpleicon` shortcode, ~11.5ms per call 473 times is 5.4395s. Combined, that is ~6.02s.

This improves the build time by ~4.24s!

2023-05-22 23:25 UTC, uncenter commented
I feel like I measured it wrong or did the calculations wrong because it seems like a big difference lmfao.

2023-05-23 01:07 UTC, ryanccn requested changes

2023-05-23 01:07 UTC, ryanccn commented on src/_layouts/base.njk
> +          {% icon "lucide:" + link.icon, class='block w-5 h-5' %}
maybe refactor the frontmatter to just include the source?

2023-05-23 01:14 UTC, ryanccn approved these changes

2023-05-23 01:17 UTC, merged